% -------------------------------------------------------------------
%  Generated by MATLAB on 29-Oct-2020 19:00:49
%  MATLAB version: 9.7.0.1319299 (R2019b) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

Hd = saveVarsMat.Hd; % <1x1 dfilt.df2sos> unsupported class

clear saveVarsMat;
